import {
  flower_1,
  flower_2,
  flower_3,
  flower_4,
  flower_6,
  flower_7,
  flowre_5,
  tab_cart,
  tab_home,
  tab_product,
} from '../assets/icons/icons';
import {
  kiki_bag,
  kiki_basket,
  kiki_cake,
  kiki_radio,
  special_jiji,
} from '../assets/images/image';

export const dummyProducts = [
  {
    id: '1',
    name: 'Totoro Plush Toy',
    price: 25.99,
    image: kiki_bag,
    description: 'A soft and huggable Totoro plush toy for all ages.',
    category: 'Toys',
  },
  {
    id: '2',
    name: 'Catbus Pillow',
    price: 19.99,
    image: flower_1,
    description: 'A cozy pillow shaped like the iconic Catbus.',
    category: 'Home',
  },
  {
    id: '3',
    name: 'Spirited Away Poster',
    price: 9.99,
    image: flower_2,
    description: 'High-quality art poster featuring Chihiro and Haku.',
    category: 'Posters',
  },
  {
    id: '4',
    name: 'No-Face Piggy Bank',
    price: 14.5,
    image: tab_home,
    description: 'Save coins with this cute No-Face piggy bank.',
    category: 'Accessories',
  },
  {
    id: '5',
    name: 'Howl’s Moving Castle Keychain',
    price: 6.5,
    image: kiki_basket,
    description: 'Miniature castle keychain inspired by Howl’s Moving Castle.',
    category: 'Accessories',
  },
  {
    id: '6',
    name: 'Kodama Glow-in-the-Dark Figurines',
    price: 12.99,
    image: kiki_cake,
    description:
      'Set of 3 glow-in-the-dark tree spirits from Princess Mononoke.',
    category: 'Toys',
  },
  {
    id: '7',
    name: 'Kiki’s Delivery Service Mug',
    price: 11.99,
    image: kiki_radio,
    description: 'Ceramic mug with Kiki and Jiji art.',
    category: 'Home',
  },
  {
    id: '8',
    name: 'Princess Mononoke Wolf Hoodie',
    price: 39.99,
    image: special_jiji,
    description: 'Comfortable hoodie featuring San and her wolf guardian.',
    category: 'Clothing',
  },
  {
    id: '9',
    name: 'Ghibli Studio Enamel Pins (Set of 4)',
    price: 17.99,
    image: flower_6,
    description: 'Collectible enamel pin set with classic characters.',
    category: 'Accessories',
  },
  {
    id: '10',
    name: 'Calcifer Candle Holder',
    price: 21.0,
    image: flower_4,
    description: 'Bring home the fire demon with this unique holder.',
    category: 'Home',
  },
  {
    id: '11',
    name: 'Totoro Umbrella',
    price: 22.99,
    image: tab_cart,
    description: 'Stay dry with a stylish Totoro-themed umbrella.',
    category: 'Accessories',
  },
  {
    id: '12',
    name: 'Laputa Robot Statue',
    price: 45.5,
    image: tab_product,
    description: 'Detailed figure of the guardian robot from Laputa.',
    category: 'Collectibles',
  },
  {
    id: '13',
    name: 'Ghibli Forest Notebook',
    price: 8.0,
    image: flower_3,
    description: 'Aesthetic forest-themed notebook for journaling.',
    category: 'Stationery',
  },
  {
    id: '14',
    name: 'Jiji Cat Plush',
    price: 18.75,
    image: flower_1,
    description: 'Soft plush of Kiki’s talking black cat.',
    category: 'Toys',
  },
  {
    id: '15',
    name: 'Totoro Slippers',
    price: 24.99,
    image: flower_2,
    description: 'Comfy indoor slippers featuring Totoro.',
    category: 'Clothing',
  },
  {
    id: '16',
    name: 'Ghibli Puzzle - 1000 Pieces',
    price: 29.99,
    image: flower_3,
    description: 'Fun challenge for fans of Studio Ghibli scenes.',
    category: 'Toys',
  },
  {
    id: '17',
    name: 'Soot Sprite Phone Case',
    price: 13.5,
    image: flower_4,
    description: 'Phone case with cute Soot Sprite patterns.',
    category: 'Accessories',
  },
  {
    id: '18',
    name: 'Ghibli Music Box',
    price: 31.0,
    image: flowre_5,
    description: 'Plays the “Path of the Wind” tune with a hand crank.',
    category: 'Home',
  },
  {
    id: '19',
    name: 'Howl’s Magic Ring Replica',
    price: 16.99,
    image: flower_6,
    description: 'Replica of Howl’s magical ring with blue gem.',
    category: 'Accessories',
  },
  {
    id: '20',
    name: 'Totoro Phone Stand',
    price: 10.0,
    image: flower_7,
    description: 'Cute phone stand for desks with Totoro base.',
    category: 'Accessories',
  },
];
